### PR TITLE
Adding portuguese translations por Andreas' video and main README

### PR DESCRIPTION
**Pull request by tiidadavena**
Adding portuguese translations por Andreas' video and main README

### CODE REVIEW

**Comment by reshamas** [comment]
@tiidadavena 
The file name has a typo:  por/1_transcript_ACM_contribuiting_sklearn_PT.md
It should be "contributing"

Are you able to delete the folder `por/`

You probably need to sync first:  `git pull upstream master`

**Comment by reshamas** [comment]
@tiidadavena 
This is getting there :)

Minor change needs to be made:  
The file name has a typo: por/1_transcript_ACM_contribuiting_sklearn_PT.md
It should be "contributing"

**Comment by tiidadavena** [comment]
Thanks for the warning! The file was renamed :D

**Comment by reshamas** [comment]
@tiidadavena 
Would you want to submit one more PR and remove the file with the misspelling.  Notice here that there are two files for Andreas' translation of video:
https://github.com/data-umbrella/data-umbrella-scikit-learn-sprint/tree/master/pt_br

**Pull request merged**
